NW = [
    "Happy Republic Day! 🇮🇳 Chalo, unity ki spirit ko celebrate karein! 💪",
    "Republic Day ki hardik shubhkaamnayein! 🇮🇳 Jai Hind! 🙏",
    "Is Republic Day par, India ki spirit ko enjoy karein! 🇮🇳✨",
    "Happy Republic Day! Humara desh hamesha chamakte rahe! 🌟🇮🇳",
    "Jai Hind! Humare freedom ke liye kiye gaye sacrifices ko salute karte hain! 🙌🇮🇳",
    "Republic Day par apni rich culture ko celebrate karein! 🇮🇳🎉",
    "Happy Republic Day! Humari heritage aur progress par garv karein! 💥🇮🇳",
    "Republic Day ki dher sari shubhkaamnayein! 🎆🇮🇳",
    "Happy Republic Day! Desh ko bright future ki taraf badhate chalein! 🌞🇮🇳",
    "Proud to be Indian! Happy Republic Day! 🇮🇳💖",
    "Chaliye, Constitution ko samman den aur apne desh ke liye kaam karein! 🇮🇳📜",
    "Bharatiya tiranga hamesha uncha rahe! 🇮🇳 Happy Republic Day! 🎉",
    "Unity, diversity aur freedom ka celebration karein! Happy Republic Day! 🇮🇳🤝",
    "Fauji bhaiyon ko salute karein jo hamare desh ki raksha karte hain! 🇮🇳👮‍♂️",
    "Republic Day ek reminder hai ki humein apne desh ko aur behtar banana hai! 💼🇮🇳",
    "Happy Republic Day! Chalo, sab milke ek behtar Bharat banayein! 🇮🇳🌏",
    "Republic Day par, humare leaders ki sacrifices ko yaad karein! 🙏🇮🇳",
    "Happy Republic Day! India hamesha strong aur united rahe! 💪🇮🇳",
    "Chalo, Republic Day ko pyar aur khushi ke saath manayein! ❤️🇮🇳",
    "Chalo, milkar India ko aur majboot banayein! 🇮🇳✊",
    "Republic Day ki dher sari shubhkaamnayein! Wishing you all happiness and pride! 🌟🇮🇳",
    "Happy Republic Day! Apne desh ko proud karne ka time hai! 🇮🇳🎉",
    "Jai Hind! Apne desh ke Constitution aur freedom ko salute karein! 🙏🇮🇳",
    "Republic Day par, desh ki safalta aur happiness ki dua karein! 🇮🇳🌸",
    "India ke heritage par garv karein! Happy Republic Day! 🇮🇳🎊",
    "Republic Day par, humare Constitution aur freedom ko samjhein! 🙌🇮🇳",
    "Happy Republic Day! Unity aur love ke saath apne desh ko aur behtar banayein! 🇮🇳💖",
    "Jai Hind! Apne desh ko hamesha strong aur united banayein! 🇮🇳🌟",
    "Republic Day ki shubhkaamnayein! Chalo, ek behtar India banayein! 💪🇮🇳",
    "Happy Republic Day! Apne desh ki growth ko celebrate karein! 🇮🇳📈",
    "Chalo, Republic Day par apne desh ke sapne ko jeevit karein! 🇮🇳✨",
    "Jai Hind! Apne Constitution ko izzat den aur future ko bright banayein! 🇮🇳🔮",
    "Republic Day ek reminder hai ki hum apne desh ko behtar banayein! 🇮🇳💼",
    "Happy Republic Day! India hamesha khush rahe aur unity mein rahe! 🇮🇳☮️",
    "Desh ki seva mein apna yogdan de kar Republic Day manayein! 🇮🇳💪",
    "Republic Day ka din hai apni deshbhakti ko dikhane ka! Jai Hind! 🇮🇳🎉",
    "Happy Republic Day! Humare desh ki safalta ko celebrate karein! 🇮🇳🌸",
    "Jai Hind! Republic Day ke din apne freedom ko yaad karein! 🇮🇳📜",
    "Happy Republic Day! India ko global stage pe aur shine karte dekhein! 🇮🇳🌍",
    "Republic Day ek naya soch aur growth ka time hai! 🇮🇳💡",
    "Happy Republic Day! Chalo, apni unity aur strength ko celebrate karein! 🇮🇳🎆",
    "Republic Day par, apne freedom aur democracy ko yaad karein! 🗳️🇮🇳",
    "Happy Republic Day! Apne desh ke liye pyar aur respect hamesha banaye rakhein! 💖🇮🇳",
    "Jai Hind! Republic Day ke din apne desh ke heroes ko salute karein! 🙏🇮🇳",
    "Republic Day par, apne democracy ko izzat dene ka time hai! 🇮🇳⚖️",
    "Happy Republic Day! Humare desh ko aur majboot banayein! 🇮🇳💪",
    "Republic Day ki shubhkaamnayein! India ke liye humesha proud feel karein! 🇮🇳❤️",
    "Chalo, Republic Day par apni duties aur responsibilities ko samjhein! 🇮🇳📚",
    "Happy Republic Day! Apne desh ki development aur progress mein yogdan dein! 🌱🇮🇳",
    "Republic Day ka matlab hai apne desh ko pyar aur izzat dena! 🇮🇳💖",
    "Jai Hind! Republic Day ke din apne desh ke Constitution ko yaad karein! 📜🇮🇳",
    "Happy Republic Day! Chalo, ek aise Bharat ki kalpna karein jo aur behtar ho! 🇮🇳✨",
    "Republic Day par, humare desh ke heroes ko yaad karein! 🇮🇳🙌",
    "Jai Hind! Republic Day ek nayi umeed ka din hai! 🇮🇳🌅",
    "Happy Republic Day! Humare desh ke liye humesha proud feel karein! 🇮🇳🎉",
    "Republic Day ki shubhkaamnayein! Apni country ko behtar banane ka waqt hai! 🇮🇳💼",
    "Jai Hind! Chalo, apne desh ke liye kuch achha karte hain! 🇮🇳💪",
    "Happy Republic Day! Apne desh ko global stage par aur chamkane ka waqt hai! 🇮🇳🌟",
    "Republic Day ka matlab hai apne desh ko aur majboot aur saaf banana! 🇮🇳🌿",
    "Chalo, Republic Day par apni unity aur democracy ko celebrate karein! 🇮🇳🎉",
    "Happy Republic Day! Desh ke liye apne contributions ko badhate chalein! 🇮🇳🚀",
    "Jai Hind! Republic Day par humare Constitution ko salute karein! 🇮🇳🙏",
    "Happy Republic Day! Apni deshbhakti ko dikhane ka ek aur din! 🇮🇳💖",
    "Republic Day par, humare desh ko aur mazboot banayein! 🇮🇳🔥",
    "Happy Republic Day! Desh ki growth aur development ko celebrate karein! 🇮🇳📈",
    "Jai Hind! Republic Day ek celebration hai apne desh ke freedom ka! 🇮🇳🎉",
    "Happy Republic Day! Apne desh ke liye apna contribution dena na bhooliye! 🇮🇳💡",
    "Republic Day par, unity aur harmony ko celebrate karein! 🇮🇳🤝",
    "Happy Republic Day! Chalo, apne desh ko aur mahan banayein! 🇮🇳✨",
    "Jai Hind! Republic Day par apne desh ki seva mein apna yogdan dein! 🇮🇳💪",
    "Republic Day ki shubhkaamnayein! Humare desh ko har din behtar banayein! 🇮🇳🚀",
    "Happy Republic Day! Apne desh ke heroes ko yaad karein aur unhe salute karein! 🇮🇳💖",
    "Jai Hind! Republic Day par apne desh ki unity aur strength ko celebrate karein! 🇮🇳💪",
    "Republic Day par, apne desh ke Constitution ko yaad karein aur izzat den! 🇮🇳📜",
    "Happy Republic Day! Apne desh ko aur better aur brighter banayein! 🇮🇳🌞",
    "Republic Day ki shubhkaamnayein! Desh ki taqat aur unity ko feel karein! 🇮🇳✊",
    "Jai Hind! Apne desh ki taqat aur sapne ko jeene ka waqt hai! 🇮🇳💖",
    "Happy Republic Day! Apne desh ke liye milke kaam karein aur sabko inspire karein! 🇮🇳🌱"
]


NW2 = [
    "Happy Vasant Panchami! Aapki zindagi mein khushiyan aur gyaan aaye. 🌼🎉",
    "Goddess Saraswati se dua hai ki aapko hamesha gyaan aur safalta mile. 📚🙏",
    "Vasant Panchami ki hardik shubhkamnaayein aapko aur aapke parivaar ko! 🌸🌿",
    "Is pavitra din pe aapki zindagi mein gyaan aur sukh ka ujala ho. 🌟📖",
    "Happy Vasant Panchami! Aapki zindagi rangon se bhari ho. 🌷🌸",
    "Garmiyon ka mausam aapki zindagi mein khushiyan le aaye. 🌸🌞",
    "Basant Panchami ki hardik subhkaamnayein! Aapki zindagi mein raushan ho. ✨💐",
    "Vasant Panchami ke is din ko hum khushi aur dosti ke saath manayein. 🌼🎶",
    "Aapko Vasant Panchami par dher saari khushiyan aur gyaan milti rahe. 🎓💛",
    "Goddess Saraswati se dua hai ki aapki zindagi hamesha roshan ho. 📚🌟",
    "Vasant Panchami ki hardik shubhkamnayein! Aapki zindagi mein pyaar aur hasrat ho. 🌼❤️",
    "Is din aap nayi shuruat karein aur apne sapne poore karein. 💖🌸",
    "Vasant Panchami ke iss din aapki zindagi mein shaanti aur gyaan aaye. 📚🕊️",
    "Vasant Panchami ki subhkamnaayein! Aapki zindagi mein safalta aur khushi aaye. 🌷🌞",
    "Goddess Saraswati se dua hai ki aapko sadaa gyaan aur safalta mile. 🙏🎶",
    "Happy Basant Panchami! Aapke saath har rang ka jashn ho. 🌺🎉",
    "Vasant Panchami par aapko dher saari safalta aur gyaan mile. 🌸✨",
    "Is din, Saraswati ji ki ashirwad se aapke jeevan mein raushan ho. 📖🌟",
    "Basant Panchami ki hardik shubhkamnayein! Aapki zindagi hamesha sukhad ho. 🌷💛",
    "Vasant Panchami ka ye tyohaar aapke jeevan mein khushiyan aur nayi umeedein laaye. 🌞🌷",
    "Aapko Saraswati ji ka ashirwad mile, har kadam par safalta mile. 📚🌸",
    "Happy Vasant Panchami! Aapki zindagi mein gyaan aur sukh aaye. 🌼💫",
    "Is Vasant Panchami, aapke jeevan mein naye rang bhar jaayein. 🌷🌿",
    "Basant Panchami ke is din, aapko gyaan aur samriddhi milti rahe. 📖🌸",
    "Vasant Panchami ki shubhkamnayein! Aapki zindagi mein raushan ho. 🕊️📚",
    "Saraswati ji ka ashirwad sada aapke saath ho, aapko har safalta mile. 📚🌟",
    "Vasant Panchami par aapka jeevan rangon se bhara rahe. 🌼🎉",
    "Happy Vasant Panchami! Aapki zindagi mein nayi umeedein ho. 🌸🎨",
    "Is pavitra tyohaar par, aapke jeevan mein hamesha gyaan aur sukh ho. 💡💖",
    "Vasant Panchami ki dher saari subhkamnaayein! Aapki zindagi mein Saraswati ji ka ashirwad ho. 📚🌼",
    "Is din, Saraswati ji ka ashirwad aapko har raaste mein madad de. 📖🌸",
    "Happy Basant Panchami! Aapke jeevan mein hamesha gyaan aur safalta ho. 🌼🎉",
    "Vasant Panchami ka tyohaar aapke jeevan ko nayi roshni de. 🌸💛",
    "Aapko Vasant Panchami par Saraswati ji ka ashirwad mile. 🙏📚",
    "May Saraswati’s blessings guide you today and always! 📚🌟",
    "Aapki zindagi mein hamesha safalta, sukh aur gyaan ho. 🌷💛",
    "Vasant Panchami ki dher saari subhkamnaayein! Aapki zindagi mein hamesha khushiyan ho. 🌸🍀",
    "May Goddess Saraswati bless you with endless wisdom and peace. 🌷📖",
    "Happy Vasant Panchami! Aapki zindagi mein dher saari safaltaayein ho. 🌼✨",
    "Vasant Panchami par Saraswati ji ka ashirwad aapko har kadam par madad de. 🌸🌟",
    "Vasant Panchami ke is din aapko khushiyon aur safalta ka ashirwad mile. 💐🌞",
    "Happy Basant Panchami! Aapki zindagi mein Saraswati ji ka ashirwad sadaa ho. 📚🌷",
    "Aapka har din, Saraswati ji ke gyaan se roshan ho. 📖✨",
    "Happy Vasant Panchami! Aapka jeevan rangon aur gyaan se bhara rahe. 🌼🎶",
    "Is din Saraswati ji ka ashirwad aapko nayi shuruat de. 📚🌸",
    "Vasant Panchami ke tyohaar par aapki zindagi mein safalta aur khushiyan ho. 💫🌷",
    "May your life always be filled with wisdom and joy. 📚💛",
    "Happy Basant Panchami! Aapke jeevan mein har kadam par Saraswati ji ka saath ho. 🙏🌼",
    "May your life be filled with happiness, knowledge, and success. 🌸✨",
    "Vasant Panchami ka tyohaar aapke liye safalta aur sukh laaye. 📖🌸",
    "Wishing you endless joy and wisdom this Vasant Panchami. 🌸📚",
    "Happy Vasant Panchami! May Goddess Saraswati bless you with knowledge. 📚🌷",
    "Aapki zindagi mein hamesha gyaan aur safalta ho. 📖💫",
    "Vasant Panchami par Saraswati ji ki blessings aapke saath rahe. 🌷🌸",
    "Happy Vasant Panchami! May your life bloom with happiness and wisdom. 🌼💛",
    "On this Vasant Panchami, may you always walk the path of knowledge and success. 📚✨",
    "Vasant Panchami ka tyohaar aapke liye ek nayi shuruat ho. 📖🌸",
    "Is Vasant Panchami, Saraswati ji aapko hamesha safalta aur gyaan den. 🙏📚",
    "Happy Vasant Panchami! Aapke jeevan mein sukh aur gyaan ka raushan ho. 🌞🌷",
    "May Saraswati bless you with wisdom and success always. 📚🌸",
    "Happy Vasant Panchami! Aapki zindagi mein Saraswati ji ka ashirwad sada rahe. 🌷📖",
    "Is Vasant Panchami, Saraswati ji aapke jeevan mein safalta aur khushiyan le aaye. 🌼📖",
    "Happy Vasant Panchami! Aapki zindagi mein Saraswati ji ki ashirwad hamesha rahe. 🌸💐",
    "On this Vasant Panchami, may your life be filled with knowledge and light. 📚🌟",
    "Happy Vasant Panchami! May Goddess Saraswati guide you towards success. 🙏📚",
    "Is din Saraswati ji ka ashirwad aapke jeevan mein shanti aur gyaan laaye. 🌷🕊️",
    "May Vasant Panchami bring endless prosperity and wisdom to your life. 📚💫",
    "Wishing you endless happiness, prosperity, and wisdom on this Vasant Panchami! 🌼📖",
    "Vasant Panchami par aapki zindagi mein Saraswati ji ka ashirwad sada ho. 🙏📚",
    "Happy Basant Panchami! Aapke jeevan mein hamesha gyaan aur sukh rahe. 🌸✨",
    "May your heart always bloom with knowledge and happiness. 🌷💖",
    "Vasant Panchami par Saraswati ji ka ashirwad aapko har raaste mein mile. 📚🌟",
    "Happy Vasant Panchami! May your life always be filled with the light of wisdom. 🌼💡",
    "May Saraswati bless you with a bright and prosperous future. 📖🌞",
    "Wishing you a blessed and prosperous Vasant Panchami! 🌸✨",
    "Vasant Panchami ki hardik shubhkamnaayein! Aapki zindagi mein hamesha gyaan rahe. 🌷📚",
    "Happy Vasant Panchami! May your life be as beautiful as the spring flowers. 🌸🌼"
]
